In [1]:
import torch
from torchvision.models import resnet18, ResNet18_Weights

In [2]:
model = resnet18(weights=ResNet18_Weights.DEFAULT)
data = torch.rand(1, 3, 64, 64)
labels = torch.rand(1, 1000)

Downloading: "https://download.pytorch.org/models/resnet18-f37072fd.pth" to /root/.cache/torch/hub/checkpoints/resnet18-f37072fd.pth
100%|██████████| 44.7M/44.7M [00:00<00:00, 124MB/s]


In [3]:
prediction = model(data) # forward pass

In [4]:
prediction

tensor([[-7.4188e-01, -5.8949e-01, -4.6407e-01, -1.1165e+00, -7.4572e-01,
          2.6694e-01, -1.8130e-01,  6.3722e-01,  4.9029e-01, -2.9178e-01,
         -9.0180e-01, -7.8629e-01, -1.7314e-01, -7.7466e-01, -7.9749e-01,
         -6.9095e-01, -9.8500e-01,  1.4570e-01, -3.4539e-01, -5.4778e-01,
         -1.5725e+00, -8.4253e-01, -1.5135e+00,  1.5582e-01, -8.9205e-01,
         -1.1909e+00, -9.0890e-01, -1.0276e+00, -7.5602e-01,  3.5149e-03,
         -9.2256e-01, -5.5079e-01, -4.9594e-01, -3.2964e-01, -2.3971e-01,
         -5.0220e-01,  5.2537e-01, -6.9592e-01, -4.1002e-01, -7.5203e-03,
         -7.7396e-01, -8.8654e-01, -1.0440e+00, -2.8295e-01, -6.3848e-01,
         -4.7383e-01, -7.6200e-01, -5.4982e-01, -1.2791e+00, -1.1110e+00,
         -6.8427e-01,  5.4119e-01, -3.5066e-01, -8.5622e-01,  2.4822e-02,
         -1.1790e+00, -3.8170e-01, -1.5653e+00, -8.5640e-01, -6.2043e-01,
          9.0607e-01,  1.9795e-01,  6.2331e-03,  1.8654e-01, -5.5671e-01,
         -6.8473e-03, -4.9136e-01, -4.

In [5]:
loss = (prediction - labels).sum()
loss.backward() # backward pass

In [6]:
optim = torch.optim.SGD(model.parameters(), lr=1e-2, momentum=0.9)

In [7]:
optim.step() # gradient descent

In [8]:
import torch

a = torch.tensor([2., 3.], requires_grad=True)
b = torch.tensor([6., 4.], requires_grad=True)

In [9]:
a, b

(tensor([2., 3.], requires_grad=True), tensor([6., 4.], requires_grad=True))

In [10]:
Q = 3*a**3 - b**2
Q

tensor([-12.,  65.], grad_fn=<SubBackward0>)

In [11]:
external_grad = torch.tensor([1., 1.])
Q.backward(gradient=external_grad)

In [12]:
# check if collected gradients are correct
print(9*a**2 == a.grad)
print(-2*b == b.grad)

tensor([True, True])
tensor([True, True])


In [13]:
x = torch.rand(5, 5)
y = torch.rand(5, 5)
z = torch.rand((5, 5), requires_grad=True)

a = x + y
print(f"Does `a` require gradients?: {a.requires_grad}")
b = x + z
print(f"Does `b` require gradients?: {b.requires_grad}")

Does `a` require gradients?: False
Does `b` require gradients?: True


`b` requires gradients because z requires grad

In [14]:
from torch import nn, optim

model = resnet18(weights=ResNet18_Weights.DEFAULT)

# Freeze all the parameters in the network
for param in model.parameters():
  param.requires_grad = False

In [15]:
model.fc = nn.Linear(512, 10)

In [16]:
# Optimize only the classifier
optimizer = optim.SGD(model.parameters(), lr=1e-2, momentum=0.9)