In [1]:
import torch
from torchvision.models import resnet18, ResNet18_Weights

In [2]:
model = resnet18(weights=ResNet18_Weights.DEFAULT)
data = torch.rand(1, 3, 64, 64)
labels = torch.rand(1, 1000)

Downloading: "https://download.pytorch.org/models/resnet18-f37072fd.pth" to /Users/mizuiro/.cache/torch/hub/checkpoints/resnet18-f37072fd.pth


URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000)>

In [6]:
prediction = model(data) # forward pass

In [7]:
prediction

tensor([[-8.2627e-01, -7.2846e-01, -7.6596e-01, -1.7972e+00, -8.7739e-01,
         -4.6642e-01, -7.4123e-01,  4.9069e-01,  2.5512e-01, -1.0326e+00,
         -1.0334e+00, -9.5563e-01, -5.1781e-01, -1.1987e+00, -1.4825e+00,
         -8.2921e-01, -9.6692e-01, -2.4614e-01, -6.8490e-01, -6.2949e-01,
         -1.8517e+00, -7.4901e-01, -1.9121e+00,  4.2123e-03, -8.7416e-01,
         -1.0157e+00, -1.0546e+00, -1.3419e+00, -8.5292e-01, -5.8420e-01,
         -8.8201e-01, -6.8255e-01, -4.7449e-01, -7.4852e-01, -4.7218e-01,
         -3.6866e-01,  7.1759e-01, -5.3729e-01, -4.9094e-01,  9.6740e-03,
         -1.0844e+00, -1.0702e+00, -1.2044e+00, -5.0899e-01, -9.7056e-01,
         -2.4937e-01, -9.6362e-01, -4.9367e-01, -1.3865e+00, -1.2766e+00,
         -6.8346e-01,  4.3076e-01, -4.0514e-01, -6.6586e-01, -4.1866e-01,
         -1.2922e+00, -5.4359e-01, -1.4959e+00, -6.8638e-01, -6.7097e-01,
          6.7659e-01,  5.1164e-02, -2.6268e-01,  1.8323e-01, -8.3820e-01,
         -4.8487e-01, -5.0787e-01, -6.

In [8]:
loss = (prediction - labels).sum()
loss.backward() # backward pass

In [9]:
optim = torch.optim.SGD(model.parameters(), lr=1e-2, momentum=0.9)

In [10]:
optim.step() # gradient descent

In [11]:
import torch

a = torch.tensor([2., 3.], requires_grad=True)
b = torch.tensor([6., 4.], requires_grad=True)

In [12]:
a, b

(tensor([2., 3.], requires_grad=True), tensor([6., 4.], requires_grad=True))

In [13]:
Q = 3*a**3 - b**2
Q

tensor([-12.,  65.], grad_fn=<SubBackward0>)

In [14]:
external_grad = torch.tensor([1., 1.])
Q.backward(gradient=external_grad)

In [15]:
# check if collected gradients are correct
print(9*a**2 == a.grad)
print(-2*b == b.grad)

tensor([True, True])
tensor([True, True])


In [ ]:
x = torc